# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/reservenow
spring.datasource.username=postgres
spring.datasource.password=Olowalu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true