package com.reservenow.user;

import jakarta.persistence.*;
import java.time.LocalDateTime;

// Represents a system user and maps to the "users" table in the database.
@Entity
@Table(name = "users")
public class User {

    // Primary key (auto-generated by the database)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Basic user information (required fields)
    @Column(nullable = false)
    private String firstName;

    @Column(nullable = false)
    private String lastName;

    // Email must be unique to prevent duplicate accounts
    @Column(nullable = false, unique = true)
    private String email;

    // Password should be hashed before being stored
    @Column(nullable = false)
    private String password;

    // Role stored as a String for readability and stability
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    // Automatically set when the user is first created
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // Constructor Required by JPA
    public User() {
    }

    // Sets creation timestamp before persisting to the database
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return password;
    }
    // Password hashing will be handled in the service layer
    public void setPassword(String password) {
        this.password = password;
    }
    public Role getRole() {
        return role;
    }
    public void setRole(Role role) {
        this.role = role;
    }
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}